---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: jenkins-rocky9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    networks:
      - name: integration-test-net
    published_ports:
      - "8080:8080/tcp"

  - name: nginx-rocky9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    privileged: true
    command: /lib/systemd/systemd
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    networks:
      - name: integration-test-net
    published_ports:
      - "80:80/tcp"
      - "443:443/tcp"
    groups:
      - nginx

provisioner:
  name: ansible
  inventory:
    host_vars:
      jenkins-server:
        ansible_user: root
      nginx-proxy:
        ansible_user: root
        jenkins_backend_host: jenkins-server
        jenkins_backend_port: 8080

verifier:
  name: testinfra

scenario:
  name: integration
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
