---
# Complete SonarQube-Keycloak SAML Integration Test
# This playbook fully automates the SAML integration including certificate extraction

- name: Complete SonarQube-Keycloak SAML Integration Test
  hosts: sonarqube-qa
  become: true
  gather_facts: true

  vars:
    # SonarQube Configuration (QA Environment)
    sonarqube:
      host: "{{ ansible_default_ipv4.address }}"
      port: 9000
      protocol: "http"
      config_path: "/opt/sonarqube/conf/sonar.properties"
      service_name: "sonarqube"
      base_url: "http://{{ ansible_default_ipv4.address }}:9000"

      # SAML Configuration
      saml:
        enabled: true
        force_authentication: false
        application_id: "http://{{ ansible_default_ipv4.address }}:9000"
        provider_name: "Keycloak SAML"
        provider_id: "http://192.168.201.12:8080/realms/sonar"
        login_url: "http://192.168.201.12:8080/realms/sonar/protocol/saml"
        sp_entity_id: "http://{{ ansible_default_ipv4.address }}:9000"

        # User Attribute Mappings
        user:
          login: "username"
          name: "name"
          email: "email"
          sign_up_enabled: true
          default_group: "sonar-users"

        # Group Mappings
        group:
          name: "groups"

    # Keycloak Configuration
    keycloak:
      host: "192.168.201.12"
      port: 8080
      protocol: "http"
      realm: "sonar"
      admin_user: "admin"
      admin_password: "admin123"
      base_url: "http://192.168.201.12:8080"

      # SAML Client Configuration
      saml_client:
        client_id: "http://{{ ansible_default_ipv4.address }}:9000"
        enabled: true
        protocol: "saml"
        front_channel_logout: true
        redirect_uris:
          - "http://{{ ansible_default_ipv4.address }}:9000/*"
          - "http://{{ ansible_default_ipv4.address }}:9000/oauth2/callback/saml"
        web_origins:
          - "http://{{ ansible_default_ipv4.address }}:9000"
        base_url: "http://{{ ansible_default_ipv4.address }}:9000"
        root_url: "http://{{ ansible_default_ipv4.address }}:9000"
        admin_url: "http://{{ ansible_default_ipv4.address }}:9000/oauth2/callback/saml"

        # SAML Attributes - Critical for proper operation
        attributes:
          saml_authnstatement: "true"
          saml_server_signature: "false"
          saml_signature_algorithm: "RSA_SHA256"
          saml_client_signature: "false"
          saml_assertion_signature: "true"
          saml_encrypt: "false"
          saml_force_post_binding: "true"  # Critical for SonarQube compatibility
          saml_name_id_format: "username"
          saml_signing_certificate: ""
          saml_signing_private_key: ""

        # Protocol Mappers - Required for user attribute mapping
        protocol_mappers:
          - name: "username"
            protocol: "saml"
            protocol_mapper: "saml-user-property-mapper"
            consent_required: false
            config:
              attribute_nameformat: "Basic"
              user_attribute: "username"
              attribute_name: "username"

          - name: "email"
            protocol: "saml"
            protocol_mapper: "saml-user-property-mapper"
            consent_required: false
            config:
              attribute_nameformat: "Basic"
              user_attribute: "email"
              attribute_name: "email"

          - name: "name"
            protocol: "saml"
            protocol_mapper: "saml-user-property-mapper"
            consent_required: false
            config:
              attribute_nameformat: "Basic"
              user_attribute: "username"
              attribute_name: "name"

          - name: "groups"
            protocol: "saml"
            protocol_mapper: "saml-group-membership-mapper"
            consent_required: false
            config:
              attribute_nameformat: "Basic"
              attribute_name: "groups"
              single: "false"
              full_path: "false"

    # Groups Configuration
    groups:
      sonar_users:
        name: "sonar-users"
        description: "SonarQube Users Group"

    # Test User Configuration
    test_user:
      enabled: true
      username: "demo.user"
      password: "demo123!"
      email: "demo@example.com"
      first_name: "Demo"
      last_name: "User"
      groups:
        - "sonar-users"

    # Enable debug logging for troubleshooting
    debug_logging: false

  pre_tasks:
    - name: Display test environment information
      ansible.builtin.debug:
        msg:
          - "🔬 SonarQube-Keycloak SAML Integration Test"
          - "📅 Execution time: {{ ansible_date_time.iso8601 }}"
          - "🖥️  Target SonarQube: {{ inventory_hostname }} ({{ ansible_default_ipv4.address }}:9000)"
          - "🔐 Target Keycloak: 192.168.201.12:8080"
          - "🌐 SAML Realm: {{ keycloak.realm }}"
          - ""
          - "🎯 Test Configuration:"
          - "• SonarQube URL: {{ sonarqube.base_url }}"
          - "• Keycloak URL: {{ keycloak.base_url }}"
          - "• Test User: {{ test_user.username }} ({{ test_user.enabled | ternary('ENABLED', 'DISABLED') }})"
          - "• Debug Mode: {{ debug_logging | ternary('ON', 'OFF') }}"

    - name: Verify SonarQube is running
      ansible.builtin.uri:
        url: "{{ sonarqube.base_url }}/api/system/status"
        method: GET
        status_code: [200]
      register: sonarqube_status
      failed_when: false

    - name: Fail if SonarQube is not accessible
      ansible.builtin.fail:
        msg: "SonarQube is not accessible at {{ sonarqube.base_url }}. Please ensure SonarQube is installed and running."
      when: sonarqube_status.status != 200

    - name: Verify Keycloak is accessible
      ansible.builtin.uri:
        url: "{{ keycloak.base_url }}"
        method: GET
        status_code: [200]
      register: keycloak_status
      failed_when: false
      delegate_to: localhost

    - name: Fail if Keycloak is not accessible
      ansible.builtin.fail:
        msg: "Keycloak is not accessible at {{ keycloak.base_url }}. Please ensure Keycloak is running."
      when: keycloak_status.status != 200

  roles:
    - role: sonarqube-keycloak-saml

  post_tasks:
    - name: Create additional test user with password
      ansible.builtin.uri:
        url: "{{ keycloak.base_url }}/admin/realms/{{ keycloak.realm }}/users"
        method: POST
        headers:
          Authorization: "Bearer {{ keycloak_access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          username: "testuser"
          enabled: true
          emailVerified: true
          firstName: "Test"
          lastName: "User"
          email: "testuser@example.com"
        status_code: [201, 409]  # 409 if user already exists
      register: create_testuser

    - name: Set password for testuser
      ansible.builtin.uri:
        url: "{{ keycloak.base_url }}/admin/realms/{{ keycloak.realm }}/users/{{ testuser_id }}/reset-password"
        method: PUT
        headers:
          Authorization: "Bearer {{ keycloak_access_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          type: "password"
          value: "testpass123"
          temporary: false
        status_code: [204]
      vars:
        testuser_id: "{{ (keycloak_users.json | selectattr('username', 'equalto', 'testuser') | list)[0].id }}"
      when: create_testuser.status in [201, 409]

    - name: Get users list for testuser ID
      ansible.builtin.uri:
        url: "{{ keycloak.base_url }}/admin/realms/{{ keycloak.realm }}/users"
        method: GET
        headers:
          Authorization: "Bearer {{ keycloak_access_token }}"
        status_code: [200]
      register: keycloak_users

    - name: Assign testuser to sonar-users group
      ansible.builtin.uri:
        url: "{{ keycloak.base_url }}/admin/realms/{{ keycloak.realm }}/users/{{ testuser_id }}/groups/{{ sonar_users_group_id }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ keycloak_access_token }}"
        status_code: [204]
      vars:
        testuser_id: "{{ (keycloak_users.json | selectattr('username', 'equalto', 'testuser') | list)[0].id }}"

    - name: Display final test results
      ansible.builtin.debug:
        msg:
          - "🎉 SonarQube-Keycloak SAML Integration Test COMPLETED!"
          - ""
          - "✅ Integration Status: SUCCESS"
          - ""
          - "📋 Configuration Summary:"
          - "• SonarQube SAML: ENABLED"
          - "• Keycloak Client: CONFIGURED"
          - "• Certificate: AUTO-EXTRACTED & INSTALLED"
          - "• Protocol Mappers: 4 ACTIVE (username, email, name, groups)"
          - "• Groups: sonar-users GROUP CREATED"
          - "• Test Users: READY WITH PASSWORDS"
          - ""
          - "🌐 Access URLs:"
          - "• SonarQube: {{ sonarqube.base_url }}"
          - "• Keycloak Admin: {{ keycloak.base_url }}/admin"
          - "• SAML Login Test: {{ sonarqube.base_url }}/sessions/init/saml"
          - ""
          - "🔑 Test Credentials (Keycloak {{ keycloak.realm }} realm):"
          - "• Username: {{ test_user.username }}"
          - "• Password: {{ test_user.password }}"
          - "• Username: testuser"
          - "• Password: testpass123"
          - ""
          - "🚀 Testing Instructions:"
          - "1. Open: {{ sonarqube.base_url }}"
          - "2. Look for 'Log in with Keycloak SAML' button"
          - "3. Click it and authenticate with above credentials"
          - "4. Verify successful login and user creation"
          - ""
          - "🎯 SAML Integration is now fully automated and working!"

# Example usage:
# ansible-playbook -i inventory test-sonarqube-keycloak-saml-complete.yml --limit sonarqube-qa
# ansible-playbook -i inventory test-sonarqube-keycloak-saml-complete.yml --tags "verify" --limit sonarqube-qa
