---
galaxy_info:
  role_name: sonarqube_stig
  namespace: jimi_automation
  author: Jimi
  description: Wrapper role to apply the RedHatOfficial RHEL8 STIG baseline with SonarQube-specific tailoring.
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 8

  galaxy_tags:
    - sonarqube
    - stig
    - disa
    - rhel8
    - hardening

dependencies: []
