---
############################################################
# STIG V-206544
# Validation - Module modification restrictions
############################################################

- name: "V-206544 | Verify function ownership"
  become: true
  become_user: postgres
  ansible.builtin.command: >
    psql -d {{ postgresql_srg_target_database }}
    -t -A -c
    "SELECT n.nspname||'.'||p.proname||':'||r.rolname
     FROM pg_proc p
     JOIN pg_namespace n ON p.pronamespace=n.oid
     JOIN pg_roles r ON p.proowner=r.oid;"
  register: v206544_functions
  changed_when: false
  tags: ['V-206544','CAT II','check']


- name: "V-206544 | Display function ownership"
  ansible.builtin.debug:
    var: v206544_functions.stdout_lines
  tags: ['V-206544','CAT II','check']
