############################################################
# PostgreSQL STIG | V-206522 Validation
############################################################

- name: Simulate application setting individual identity
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -c "SET application_name = 'john.doe'; SELECT 1;"
  tags:
    - audit
    - V-206522

- name: Check log for captured individual identity
  become: true
  ansible.builtin.shell: |
    grep -i "john.doe" {{ pg_data_dir }}/log/* | tail -1
  register: identity_check
  changed_when: false
  failed_when: identity_check.stdout == ""
  tags:
    - audit
    - V-206522
