---
############################################################
# STIG V-206580
# Validation - Session termination enforcement
############################################################

- name: V-206580 | Check idle_session_timeout
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -t -A -c "SHOW idle_session_timeout;"
  register: v206580_idle
  changed_when: false

- name: V-206580 | Assert idle_session_timeout set
  ansible.builtin.assert:
    that:
      - v206580_idle.stdout != "0"
    fail_msg: >
      STIG V-206580 FAILED:
      idle_session_timeout not configured.
    success_msg: >
      STIG V-206580 PASSED:
      idle_session_timeout configured.
  tags:
    - stig
    - V-206580
    - cat2


- name: V-206580 | Check idle_in_transaction_session_timeout
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -t -A -c "SHOW idle_in_transaction_session_timeout;"
  register: v206580_tx
  changed_when: false

- name: V-206580 | Assert idle transaction timeout set
  ansible.builtin.assert:
    that:
      - v206580_tx.stdout != "0"
    fail_msg: >
      STIG V-206580 FAILED:
      idle_in_transaction_session_timeout not configured.
    success_msg: >
      STIG V-206580 PASSED:
      idle_in_transaction_session_timeout configured.
  tags:
    - stig
    - V-206580
    - cat2
