############################################################
# PostgreSQL STIG | V-206524 Validation
# Allow designated personnel to select auditable events
############################################################

- name: Verify only authorized roles are superusers
  become: true
  become_user: postgres
  command: psql -tAc "SELECT rolname FROM pg_roles WHERE rolsuper = true;"
  register: superuser_list
  changed_when: false