---
############################################################
# STIG V-206539
# Validation - Audit information protected from modification
############################################################

- name: V-206539 | Check log directory permissions
  become: true
  ansible.builtin.stat:
    path: "{{ postgresql_srg_log_directory }}"
  register: v206539_logdir
  tags:
    - stig
    - V-206539
    - cat2

- name: V-206539 | Check log file permissions
  become: true
  ansible.builtin.find:
    paths: "{{ postgresql_srg_log_directory }}"
    file_type: file
  register: v206539_logfiles
  tags:
    - stig
    - V-206539
    - cat2

- name: V-206539 | Validate directory protection
  ansible.builtin.assert:
    that:
      - v206539_logdir.stat.mode | int(base=8) <= 700
      - v206539_logdir.stat.pw_name == "postgres"
    fail_msg: >
      STIG V-206539 FAILED:
      Log directory not properly protected.
    success_msg: >
      Log directory protection compliant.
  tags:
    - stig
    - V-206539
    - cat2

- name: V-206539 | Validate log file ownership
  ansible.builtin.assert:
    that:
      - v206539_logfiles.files | rejectattr('pw_name', 'equalto', 'postgres') | list | length == 0
    fail_msg: >
      STIG V-206539 FAILED:
      One or more log files not owned by postgres.
    success_msg: >
      Log files protected from modification.
  when: v206539_logfiles.matched > 0
  tags:
    - stig
    - V-206539
    - cat2
