############################################################
# Validation for V-206533
############################################################

- name: Generate test log entry
  become: true
  become_user: postgres
  command: psql -c "SELECT 1;"
  tags:
    - audit
    - V-206533

- name: Check log contains user name
  become: true
  shell: |
    tail -n 5 {{ pg_data_dir }}/log/*
  register: log_sample
  changed_when: false
  tags:
    - audit
    - V-206533

- name: Fail if user name is not present in logs
  fail:
    msg: "User name is not present in PostgreSQL logs."
  when: "'postgres' not in log_sample.stdout"
  tags:
    - audit
    - V-206533
