---
############################################################
# STIG Control: V-263611
#
# Validation:
# Confirm that password blacklist updates occur through
# enterprise identity management policy mechanisms.
############################################################

- name: "V-263611 | Procedural validation"
  ansible.builtin.debug:
    msg: "Password blacklist update frequency enforced through organizational password policy."
  tags: ['V-263611','CAT II','check']
