---
############################################################
# STIG V-206561 Enforcement
# Prevent Display of Authentication Secrets
############################################################

############################################################
# Secure .pgpass Files
############################################################

- name: "V-206561 | Find .pgpass files"
  become: true
  ansible.builtin.find:
    paths:
      - /var/lib/pgsql
      - /home
      - /root
    patterns: ".pgpass"
    recurse: true
  register: postgresql_srg_pgpass_files


- name: "V-206561 | Enforce secure permissions on .pgpass"
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: postgres
    group: postgres
    mode: '0600'
  loop: "{{ postgresql_srg_pgpass_files.files }}"
  when: postgresql_srg_pgpass_files.matched > 0


############################################################
# Prevent Password Logging
############################################################

- name: "V-206561 | Disable logging of sensitive statements"
  become: true
  ansible.builtin.lineinfile:
    path: "{{ postgresql_srg_conf_file }}"
    regexp: '^#?log_statement'
    line: "log_statement = 'ddl'"
  notify: Restart PostgreSQL


############################################################
# Prevent Password Exposure in Logs
############################################################

- name: "V-206561 | Ensure log_connections enabled"
  become: true
  ansible.builtin.lineinfile:
    path: "{{ postgresql_srg_conf_file }}"
    regexp: '^#?log_connections'
    line: "log_connections = on"
  notify: Restart PostgreSQL


- name: "V-206561 | Ensure log_disconnections enabled"
  become: true
  ansible.builtin.lineinfile:
    path: "{{ postgresql_srg_conf_file }}"
    regexp: '^#?log_disconnections'
    line: "log_disconnections = on"
  notify: Restart PostgreSQL


############################################################
# Restrict Access to PostgreSQL Configuration Files
############################################################

- name: "V-206561 | Secure PostgreSQL configuration permissions"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: postgres
    group: postgres
    mode: "0600"
  loop:
    - "{{ postgresql_srg_conf_file }}"
    - "{{ postgresql_srg_hba_file }}"
