---
############################################################
# Validate Superuser Restriction
############################################################

- name: "V-206539 | Check superuser accounts"
  become_user: postgres
  ansible.builtin.shell: |
    psql -t -A -c "SELECT rolname FROM pg_roles WHERE rolsuper = true;"
  register: v206539_superusers
  changed_when: false
  tags: ['V-206539', 'CAT II', 'check']


- name: "V-206539 | Assert superuser restriction"
  ansible.builtin.assert:
    that:
      - v206539_superusers.stdout_lines | length == 1
      - "'postgres' in v206539_superusers.stdout_lines"
    fail_msg: >
      STIG V-206539 FAILED:
      Unauthorized user could modify audit data.
    success_msg: >
      PostgreSQL audit information protected from modification.
  tags: ['V-206539', 'CAT II', 'check']
