---
############################################################
# STIG Control: V-206639
#
# Title:
# DBMS must use NIST FIPS validated cryptographic modules
# to provision digital signatures.
#
# Implementation:
# PostgreSQL relies on OpenSSL provided by RHEL. When the
# system operates in FIPS mode, cryptographic operations
# use FIPS validated modules.
############################################################

- name: "V-206639 | Check FIPS mode"
  ansible.builtin.command: cat /proc/sys/crypto/fips_enabled
  register: fips_status
  changed_when: false
  tags: ['V-206639', 'CAT II', 'validate']

- name: "V-206639 | Display FIPS status"
  ansible.builtin.debug:
    var: fips_status.stdout
  tags: ['V-206639', 'CAT II', 'validate']
