---
############################################################
# STIG Control: V-263604
#
# Validation:
# Confirm audit logs are forwarded to centralized
# monitoring or SIEM platform for analysis.
############################################################

- name: "V-263604 | Check logging collector"
  become_user: postgres
  ansible.builtin.command: psql -t -c "SHOW logging_collector;"
  register: logging_collector
  changed_when: false
  tags: ['V-203604', 'CAT II', 'validate']

- name: "V-263604 | Display logging collector status"
  ansible.builtin.debug:
    var: logging_collector.stdout
  tags: ['V-203604', 'CAT II', 'validate']
