---
############################################################
# STIG Control: V-263602 Validation
#
# Verify PostgreSQL role expiration settings.
############################################################

- name: "V-263602 | Validate role expiration settings"
  become_user: postgres
  ansible.builtin.command: >
    psql -t -c "SELECT rolname, rolvaliduntil FROM pg_roles;"
  register: validate_role_expiration
  changed_when: false
  tags: ['V-203602', 'CAT II', 'validate']

- name: "V-263602 | Show role expiration values"
  ansible.builtin.debug:
    var: validate_role_expiration.stdout_lines
  tags: ['V-203602', 'CAT II', 'validate']
