---
############################################################
# STIG Control: V-206635 Validation
############################################################

- name: "V-206635 | Check log_connections"
  become: true
  become_user: postgres
  command: psql -t -c "SHOW log_connections;"
  register: log_connections
  changed_when: false
  tags: ['V-206635', 'CAT II', 'validate']

- name: "V-206635 | Check log_disconnections"
  become: true
  become_user: postgres
  command: psql -t -c "SHOW log_disconnections;"
  register: log_disconnections
  changed_when: false
  tags: ['V-206635', 'CAT II', 'validate']

- name: "Display results"
  debug:
    msg:
      - "log_connections: {{ log_connections.stdout }}"
      - "log_disconnections: {{ log_disconnections.stdout }}"
  tags: ['V-206635', 'CAT II', 'validate']
