---
############################################################
# Validation
############################################################

- name: "V-206551 | Check listen_addresses"
  become_user: postgres
  ansible.builtin.command: >
    psql -t -c "SHOW listen_addresses;"
  register: v206551_listen_addresses
  changed_when: false
  tags: ['V-206551', 'CAT II', 'check']


- name: "V-206551 | Check WAL senders"
  become_user: postgres
  ansible.builtin.command: >
    psql -t -c "SHOW max_wal_senders;"
  register: v206551_wal_senders
  changed_when: false
  tags: ['V-206551', 'CAT II', 'check']


- name: "V-206551 | Check replication slots"
  become_user: postgres
  ansible.builtin.command: >
    psql -t -c "SHOW max_replication_slots;"
  register: v206551_replication_slots
  changed_when: false
  tags: ['V-206551', 'CAT II', 'check']


- name: "V-206551 | Check WAL level"
  become_user: postgres
  ansible.builtin.command: >
    psql -t -c "SHOW wal_level;"
  register: v206551_wal_level
  changed_when: false
  tags: ['V-206551', 'CAT II', 'check']


- name: "V-206551 | Display validation results"
  ansible.builtin.debug:
    msg:
      - "listen_addresses: {{ v206551_listen_addresses.stdout }}"
      - "max_wal_senders: {{ v206551_wal_senders.stdout }}"
      - "max_replication_slots: {{ v206551_replication_slots.stdout }}"
      - "wal_level: {{ v206551_wal_level.stdout }}"
  tags: ['V-206551', 'CAT II', 'check']
