---
############################################################
# STIG Control: V-263605
#
# Validation:
# Verify audit logs are generated and forwarded to
# enterprise monitoring systems where alerting is configured.
############################################################

- name: "V-263605 | Check log destination"
  become_user: postgres
  ansible.builtin.command: psql -t -c "SHOW log_destination;"
  register: log_destination
  changed_when: false
  tags: ['V-203605', 'CAT II', 'validate']

- name: "V-263605 | Display log destination"
  ansible.builtin.debug:
    var: log_destination.stdout
  tags: ['V-203605', 'CAT II', 'validate']
