---
############################################################
# STIG Control: V-206642 Validation
############################################################

- name: "V-206642 | Check PostgreSQL log destination"
  become_user: postgres
  ansible.builtin.command: >
    psql -t -c "SHOW log_destination;"
  register: log_destination
  changed_when: false
  tags: ['V-206642', 'CAT II', 'validate']

- name: "V-206642 | Display log destination"
  ansible.builtin.debug:
    var: log_destination.stdout
  tags: ['V-206642', 'CAT II', 'validate']
