---
############################################################
# STIG V-206523
# Validation - Audit Record Generation
############################################################

- name: "V-206523 | Gather audit settings"
  become_user: postgres
  ansible.builtin.shell: |
    psql -t -A -c "SELECT current_setting('log_connections')
    UNION ALL SELECT current_setting('log_disconnections')
    UNION ALL SELECT current_setting('log_statement')
    UNION ALL SELECT current_setting('shared_preload_libraries')
    UNION ALL SELECT current_setting('pgaudit.log', true)
    UNION ALL SELECT current_setting('pgaudit.log_catalog', true);"
  register: v206523_settings
  changed_when: false
  tags: [V-206523, stig, cat2]

- name: "V-206523 | Parse settings"
  ansible.builtin.set_fact:
    v206523_list: "{{ v206523_settings.stdout_lines }}"
  tags: [V-206523, stig, cat2]

- name: "V-206523 | Assert DoD audit coverage"
  ansible.builtin.assert:
    that:
      - "'on' in v206523_list[0]"
      - "'on' in v206523_list[1]"
      - "'ddl' in v206523_list[2]"
      - "'pgaudit' in v206523_list[3]"
      - "'read' in v206523_list[4]"
      - "'write' in v206523_list[4]"
      - "'ddl' in v206523_list[4]"
      - "'role' in v206523_list[4]"
      - "'on' in v206523_list[5]"
    fail_msg: >
      STIG V-206523 FAILED:
      Required DoD auditable events are not fully configured.
    success_msg: >
      STIG V-206523 PASSED:
      Required DoD auditable events are properly configured.
  tags: [V-206523, stig, cat2]
