---
############################################################
# STIG V-206540
# Validation - Audit logs protected from deletion
############################################################

- name: "V-206540 | Validate log directory permissions"
  become: true
  ansible.builtin.stat:
    path: "{{ postgresql_srg_log_directory }}"
  register: v206540_logdir
  tags: ['V-206540', 'CAT II', 'check']


- name: "V-206540 | Assert directory protection"
  ansible.builtin.assert:
    that:
      - v206540_logdir.stat.pw_name == "postgres"
      - v206540_logdir.stat.mode == "0700"
    fail_msg: >
      STIG V-206540 FAILED:
      Log directory permissions are not secure.
    success_msg: >
      PostgreSQL audit logs protected from unauthorized deletion.
  tags: ['V-206540', 'CAT II', 'check']
