---
############################################################
# STIG V-206542
# Validation - Audit configuration protected
############################################################

- name: "V-206542 | Check superuser roles"
  become_user: postgres
  ansible.builtin.command: >
    psql -t -A -c "SELECT rolname FROM pg_roles WHERE rolsuper=true;"
  register: v206542_superusers
  changed_when: false
  tags: ['V-206542', 'CAT II', 'check']


- name: "V-206542 | Assert authorized superusers only"
  ansible.builtin.assert:
    that:
      - v206542_superusers.stdout_lines | difference(postgresql_srg_authorized_superusers) | length == 0
    fail_msg: >
      STIG V-206542 FAILED:
      Unauthorized superuser can modify audit configuration.
    success_msg: >
      Audit configuration protected from unauthorized modification.
  tags: ['V-206542', 'CAT II', 'check']
