---
############################################################
# STIG V-206541
# Validation - Audit features protected
############################################################

- name: "V-206541 | Check superuser roles"
  become_user: postgres
  ansible.builtin.command: >
    psql -t -A -c "SELECT rolname FROM pg_roles WHERE rolsuper=true;"
  register: v206541_superusers
  changed_when: false
  tags: ['V-206541', 'CAT II', 'check']


- name: "V-206541 | Assert authorized superusers only"
  ansible.builtin.assert:
    that:
      - v206541_superusers.stdout_lines | difference(postgresql_srg_authorized_superusers) | length == 0
    fail_msg: >
      STIG V-206541 FAILED:
      Unauthorized superuser could access audit features.
    success_msg: >
      Audit features protected by restricted superuser access.
  tags: ['V-206541', 'CAT II', 'check']
