---
############################################################
# STIG Control: V-206641 Validation
############################################################

- name: "V-206641 | Check system crypto policy"
  ansible.builtin.command: update-crypto-policies --show
  register: crypto_policy
  changed_when: false
  tags: ['V-206641', 'CAT II', 'validate']

- name: "V-206641 | Display crypto policy"
  ansible.builtin.debug:
    var: crypto_policy.stdout
  tags: ['V-206641', 'CAT II', 'validate']
