---
############################################################
# STIG Control Validation: V-263622
#
# Purpose:
# Verify the system clock is synchronized with the
# organization-authorized NTP source.
############################################################

- name: "V-263622 | Check system time synchronization"
  ansible.builtin.command:
    cmd: timedatectl status
  register: v263622_time_status
  changed_when: false
  tags:
    - V-263622
    - CATII
    - validate


- name: "V-263622 | Verify system clock synchronized"
  ansible.builtin.assert:
    that:
      - "'System clock synchronized: yes' in v263622_time_status.stdout"
    fail_msg: "STIG V-263622 FAILED - system clock not synchronized"
    success_msg: "STIG V-263622 PASSED - system clock synchronized"
  tags:
    - V-263622
    - CATII
    - validate
