# tasks/common/normalize.yml

- name: "Normalize schema list"
  set_fact:
    postgresql_srg_effective_schemas: >-
      {{
        postgresql_srg_application_schemas
        | flatten
        | map('trim')
        | reject('equalto','')
        | difference(['pg_catalog','information_schema'])
        | list
      }}
  tags: ['always','normalize','postgres','stig']