---
############################################################
# STIG V-206519
# Enforcement - Limit Concurrent Sessions Per Role
############################################################

- name: "V-206519 | Gather current role connection limits"
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -t -A -F',' -c "SELECT rolname, rolconnlimit FROM pg_roles;"
  register: postgresql_srg_connlimit_raw
  changed_when: false
  tags:
    - V-206519
    - stig
    - cat2

- name: "V-206519 | Parse role connection limits"
  ansible.builtin.set_fact:
    postgresql_srg_roles_parsed: >-
      {{
        postgresql_srg_connlimit_raw.stdout_lines
        | map('split', ',')
        | list
      }}
  tags:
    - V-206519
    - stig
    - cat2

- name: "V-206519 | Enforce connection limits per role"
  become: true
  become_user: postgres
  ansible.builtin.shell: >
    psql -c "ALTER ROLE {{ item[0] }}
    CONNECTION LIMIT
    {{
      (item[0] in postgresql_srg_admin_roles)
      | ternary(postgresql_srg_admin_conn_limit,
                postgresql_srg_user_conn_limit)
    }};"
  loop: "{{ postgresql_srg_roles_parsed }}"
  when:
    - item[0] not in postgresql_srg_connlimit_exempt_roles
    - not item[0].startswith('pg_')
    - item[1] | int != (
        (item[0] in postgresql_srg_admin_roles)
        | ternary(postgresql_srg_admin_conn_limit,
                  postgresql_srg_user_conn_limit)
      )
  tags:
    - V-206519
    - stig
    - cat2
