############################################################
# PostgreSQL STIG | V-206519
# Ensure Denial of Privilege Escalation is Logged
############################################################

- name: V-206519 | Ensure logging_collector is enabled
  become: true
  lineinfile:
    path: "{{ pg_conf_file }}"
    regexp: '^\s*#?\s*logging_collector\s*='
    line: "logging_collector = on"
    backup: true
  notify: Restart PostgreSQL
  tags:
    - stig
    - V-206519
    - logging

- name: V-206519 | Ensure log_destination is stderr
  become: true
  lineinfile:
    path: "{{ pg_conf_file }}"
    regexp: '^\s*#?\s*log_destination\s*='
    line: "log_destination = 'stderr'"
  notify: Restart PostgreSQL
  tags:
    - stig
    - V-206519
    - logging

- name: V-206519 | Ensure log_min_messages is error
  become: true
  lineinfile:
    path: "{{ pg_conf_file }}"
    regexp: '^\s*#?\s*log_min_messages\s*='
    line: "log_min_messages = error"
  notify: Restart PostgreSQL
  tags:
    - stig
    - V-206519
    - logging

- name: V-206519 | Ensure log_min_error_statement is error
  become: true
  lineinfile:
    path: "{{ pg_conf_file }}"
    regexp: '^\s*#?\s*log_min_error_statement\s*='
    line: "log_min_error_statement = error"
  notify: Restart PostgreSQL
  tags:
    - stig
    - V-206519
    - logging
