---
############################################################
# STIG V-206559 Enforcement
# No DBMS PKI Private Keys Present
############################################################

############################################################
# Ensure SSL is Disabled
############################################################

- name: "V-206559 | Disable SSL"
  become: true
  ansible.builtin.lineinfile:
    path: "{{ postgresql_srg_conf_file }}"
    regexp: '^#?ssl\s*='
    line: "ssl = off"
  notify: Restart PostgreSQL

############################################################
# Remove server private key if present
############################################################

- name: "V-206559 | Remove server.key if exists"
  become: true
  ansible.builtin.file:
    path: "{{ postgresql_srg_data_dir }}/server.key"
    state: absent

- name: "V-206559 | Remove server.crt if exists"
  become: true
  ansible.builtin.file:
    path: "{{ postgresql_srg_data_dir }}/server.crt"
    state: absent
