---
############################################################
# STIG V-206550
# Enforcement - Remove unused DB components
############################################################
#
# COMPLIANT WHEN:
# - Only approved extensions installed
# - Only approved procedural languages installed
# - No unused PostgreSQL packages present
# comment: The PostgreSQL installation has been reviewed. Only mission-required components, extensions, procedural languages, and DBMS software packages are installed. Unused components and features have been removed. Therefore, V-206550 is Not a Finding.
############################################################

############################
# Remove Unauthorized Extensions
############################

- name: V-206550 | Get installed extensions
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -d {{ postgresql_srg_target_database }} -t -A -c \
    "SELECT extname FROM pg_extension;"
  register: v206550_ext
  changed_when: false
  tags:
    - stig
    - V-206550
    - cat2

- name: V-206550 | Remove unauthorized extensions
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -d {{ postgresql_srg_target_database }} -c \
    "DROP EXTENSION IF EXISTS {{ item }} CASCADE;"
  loop: "{{ v206550_ext.stdout_lines }}"
  when: item not in postgresql_srg_allowed_extensions
  ignore_errors: true
  tags:
    - stig
    - V-206550
    - cat2


############################
# Remove Unauthorized Procedural Languages
############################

- name: V-206550 | Get installed languages
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -t -A -c \
    "SELECT lanname FROM pg_language WHERE lanname NOT IN ('internal','c');"
  register: v206550_lang
  changed_when: false
  tags:
    - stig
    - V-206550
    - cat2

- name: V-206550 | Remove unauthorized languages
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -c "DROP LANGUAGE IF EXISTS {{ item }};"
  loop: "{{ v206550_lang.stdout_lines }}"
  when: item not in postgresql_srg_allowed_languages
  ignore_errors: true
  tags:
    - stig
    - V-206550
    - cat2


############################
# Remove Unauthorized PostgreSQL Packages (RHEL)
############################

- name: V-206550 | Gather installed PostgreSQL packages
  become: true
  ansible.builtin.shell: |
    rpm -qa | grep postgresql
  register: v206550_pkgs
  changed_when: false
  tags:
    - stig
    - V-206550
    - cat2

- name: V-206550 | Remove unauthorized PostgreSQL packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ v206550_pkgs.stdout_lines }}"
  when: item not in postgresql_srg_allowed_packages
  ignore_errors: true
  tags:
    - stig
    - V-206550
    - cat2
