---
- name: reload postgresql
  become: true
  ansible.builtin.systemd:
    name: "{{ postgresql_stig_service_name }}"
    state: reloaded

- name: restart postgresql
  become: true
  ansible.builtin.systemd:
    name: "{{ postgresql_stig_service_name }}"
    state: restarted
