---
############################################################
# Handlers - STIG FreeIPA
############################################################

- name: restart httpd
  become: true
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: reload httpd
  become: true
  ansible.builtin.service:
    name: httpd
    state: reloaded

- name: restart auditd
  become: true
  ansible.builtin.command: service auditd restart
  changed_when: true

- name: reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: reload audit rules
  become: true
  ansible.builtin.command: augenrules --load
  changed_when: true

- name: restart named-pkcs11
  become: true
  ansible.builtin.command: "ipactl restart {{ dns_service_name | default('named-pkcs11') }}"
  changed_when: true

- name: restart systemd-journald
  become: true
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
