---
############################################################
# STIG V-206605 Validation
############################################################

############################################################
# Validate crypto policy
############################################################

- name: "V-206605 | Check crypto policy"
  become: true
  ansible.builtin.command: update-crypto-policies --show
  register: postgresql_srg_crypto_policy
  changed_when: false

- name: "Assert crypto policy is FIPS"
  ansible.builtin.assert:
    that:
      - postgresql_srg_crypto_policy.stdout is search("FIPS")
    fail_msg: "System crypto policy not set to FIPS"
    success_msg: "System crypto policy set to FIPS"

############################################################
# Validate PostgreSQL uses OpenSSL
############################################################

- name: "V-206605 | Check PostgreSQL SSL library"
  become: true
  become_user: postgres
  ansible.builtin.shell: |
    psql -tAc "SHOW ssl_library;"
  register: postgresql_srg_ssl_library
  changed_when: false

- name: "Assert PostgreSQL uses OpenSSL"
  ansible.builtin.assert:
    that:
      - postgresql_srg_ssl_library.stdout is search("OpenSSL")
    fail_msg: "PostgreSQL not using OpenSSL crypto library"
    success_msg: "PostgreSQL using OpenSSL cryptographic library"

############################################################
# Validate localhost-only binding
############################################################

- name: "V-206605 | Check listen_addresses"
  become: true
  ansible.builtin.shell: |
    grep -E "^listen_addresses" {{ postgresql_srg_conf_file }}
  register: postgresql_srg_listen_check
  changed_when: false

- name: "Assert PostgreSQL restricted to localhost"
  ansible.builtin.assert:
    that:
      - postgresql_srg_listen_check.stdout is search("localhost")
    fail_msg: "PostgreSQL exposed beyond localhost"
    success_msg: "PostgreSQL restricted to localhost"
