---
############################################################
# STIG V-206559
# Validation Tasks
############################################################

############################################################
# Check for PostgreSQL private key
############################################################

- name: "V-206559 | Check server.key presence"
  become: true
  ansible.builtin.stat:
    path: "{{ postgresql_srg_data_dir }}/server.key"
  register: postgresql_srg_key_validation

############################################################
# Validate key permissions
############################################################

- name: "V-206559 | Validate server.key permissions"
  ansible.builtin.assert:
    that:
      - postgresql_srg_key_validation.stat.exists == false
        or postgresql_srg_key_validation.stat.mode == "0600"
    fail_msg: "server.key permissions insecure"
    success_msg: "server.key protected or not present"

############################################################
# Validate FIPS crypto module
############################################################

- name: "V-206559 | Check FIPS provider"
  become: true
  ansible.builtin.shell: |
    openssl list -providers
  register: postgresql_srg_fips_validation
  changed_when: false
  when: postgresql_srg_fips_required | bool

- name: "Assert FIPS module available"
  ansible.builtin.assert:
    that:
      - postgresql_srg_fips_validation.stdout is search("fips")
    fail_msg: "FIPS cryptographic provider not detected"
    success_msg: "FIPS cryptographic module present"
  when: postgresql_srg_fips_required | bool
