---
- name: restart wazuh-manager
  systemd:
    name: "{{ wazuh_manager_service }}"
    state: restarted
  listen: restart wazuh-manager

- name: restart wazuh-indexer
  systemd:
    name: "{{ wazuh_indexer_service }}"
    state: restarted
  listen: restart wazuh-indexer

- name: restart wazuh-dashboard
  systemd:
    name: "{{ wazuh_dashboard_service }}"
    state: restarted
  listen: restart wazuh-dashboard
