############################################################
# PostgreSQL STIG | V-206528
# Ensure audit records include event type
############################################################

- name: Ensure pgaudit is enabled
  become: true
  lineinfile:
    path: "{{ pg_conf_file }}"
    regexp: '^\s*#?\s*shared_preload_libraries\s*='
    line: "shared_preload_libraries = 'pgaudit'"
    backup: true
  notify: Restart PostgreSQL
  tags:
    - stig
    - V-206528

- name: Configure pgaudit event classes
  become: true
  lineinfile:
    path: "{{ pg_conf_file }}"
    regexp: '^\s*#?\s*pgaudit\.log\s*='
    line: "pgaudit.log = 'ddl, role, write'"
  notify: Restart PostgreSQL
  tags:
    - stig
    - V-206528

- name: Enable catalog auditing
  become: true
  lineinfile:
    path: "{{ pg_conf_file }}"
    regexp: '^\s*#?\s*pgaudit\.log_catalog\s*='
    line: "pgaudit.log_catalog = on"
  notify: Restart PostgreSQL
  tags:
    - stig
    - V-206528
